# GitHub Sponsors funding configuration
# Uncomment and add your funding platforms

# github: [RButler114]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://paypal.me/username', 'https://www.buymeacoffee.com/username']
